Website/Website/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^register/',include('register.urls')),
    url(r'^admin/', admin.site.urls),
]

Website/register/urls.py
from django.conf.urls import url
from . import views

app_name='register'
urlpatterns=[
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    url(r'^new$',views.new,name='new'),
    url(r'^new/thanks$',views.thanks,name='thanks'),
]

Website/register/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

class Users(models.Model):
    name=models.CharField(max_length=200)
    rollno=models.IntegerField(default=0)
    date=models.DateTimeField('date published')
    def __str__(self):
        return self.name
        
    

# Create your models here.

Website/register/forms.py
from django import forms

class NameForm(forms.Form):
    your_name=forms.CharField(label='Your name',max_length=200)
    your_roll=forms.IntegerField(label="Your Roll number")

Website/register/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect,HttpResponse
from .models import Users
from django.core.urlresolvers import reverse
from django.views import generic
from .forms import NameForm
from django.utils import timezone

class IndexView(generic.ListView):
    template_name='register/index.html'
    context_object_name='NameList'
    
    def get_queryset(self):
        return Users.objects.order_by('rollno')[:5]


# Create your views here.
class DetailView(generic.DetailView):
    model=Users
    template_name='register/detail.html'
    
global context
def thanks(request):
    #u=Users(name="hello",rollno=31312,date=timezone.now())
    #u.save()
    return render(request,'register/thanks.html')

def new(request):
    if request.method=="post":
        form=NameForm(request.POST)
        if form.is_valid():
            n=form.cleaned_data['your_name']
            r=form.cleaned_data['your_roll']
            d=timezone.now()
            print "Here"
            ctx={}
            ctx['result'] =request.POST.get('your_name')
            return render(request,'register/thanks.html',ctx)
    else:
        print "I am here "
        form=NameForm()
    return render(request,'register/new.html',{'form':form})

Website/register/templates/register/detail.html
<html>
<head>
</head>
<title>Register applications </title>
    <body>
        {{users.name}}
        {{users.id}}
        {{users.rollno}}
        {{users.date}}
    </body>
</html>

Website/register/templates/register/index.html
<html>
<head>
</head>
<title>Register applications </title>
    <body>
        {% if NameList %}
        <ul>
            {% for names in NameList %}
                <li><a href="{% url 'register:detail' names.id %}">{{names.name}}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <p>No names available </p>
        {% endif %}
        <h3><a href="{% url 'register:new'%}">Register new user</a></h3>
    </body>
</html>

Website/register/templates/register/new.html
<html>
<head>
</head>
<title>Register applications </title>
    <body>
        <h1>Register yourself</h1>
        <form action="{% url 'register:thanks' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="register"/>
        </form>
    </body>
</html>

Website/register/templates/register/thanks.html
<h2>thanks</h2>
{{result}}